apiVersion: v1
kind: ConfigMap
metadata:
  name: problem-backend-config
  namespace: my-app
data:
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  SPRING_JPA_SHOW_SQL: "true"
  SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect

  SPRING_CONFIG_URI: http://config-server-service:8888
  SPRING_PROFILES_ACTIVE: native
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql-problem-service:3306/application_problemdb
  SPRING_DATASOURCE_USERNAME: root
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server.my-app.svc.cluster.local:8761/eureka
  
