apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-backend-config
  namespace: my-app
data:
  SPRING_JPA_HIBERNATE_DDL_AUTO: validate
  SPRING_JPA_SHOW_SQL: "true"
  SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect

  SPRING_CONFIG_URI: http://config-server-service:8888
  SPRING_PROFILES_ACTIVE: native
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql-auth-service:3306/application_auth_db
  SPRING_DATASOURCE_USERNAME: root
  SPRING_REDIS_HOST: redis

 